### ISSUE TITLE
configure grsec kernel options

### ISSUE THREAD

**Issue by 0xmikey** [0xmikey/hardened-debian#3]
The script `build.sh` in the grsec-hardened-stable-kernel branch works up untill the `make menuconfig` command in [this guide](https://micahflee.com/2016/01/debian-grsecurity/). To semi automate this, I think I can prompt the user for the required information, VM technology for example, write the answers to a file and pass that file to the `make config` tool.

**Comment by MikeyJck** [comment]
We now have a premade .config for automating the kernel build added here e6abe89c8535bcf7ca076989597662238c93c0de. 

From the commit message 

```
based on Debian Jessie 8.5 kernel with grsec enabled.
grsec options: 
Config Method:   Auto
Usage Type:      Server
VHardware:       First-gen/No
VSoftware:       VMWare 
Priorities:     Security
```

This is build for VMWare for my own testing need to patch `.config` with the users choice of VM technology they're using, if at all. Probably best to ask for this at the start to get it out the way.

**Comment by 0xmikey** [comment]
Dropping grsec support as the they no longer publish any patches to the public, testing maintenance has been handed over to the community. https://grsecurity.net/passing_the_baton.php
