### ISSUE TITLE
SSH - Key Exchange Algorithm (KexAlgorithms) Selection 

### ISSUE THREAD

**Issue by 0xmikey** [0xmikey/hardened-debian#8]
Currently we support only `curve25519` & `diffie-hellman-group-exchange-sha256`, NIST curves are [not enabled](https://blog.cr.yp.to/20140323-ecdsa.html). 

- `curve25519` works out of the box with [OpenSSH 6.5](https://www.openssh.com/txt/release-6.5) and later. 

- `diffie-hellman-group-exchange-sha256` on the other hand requires **safe** custom parameters in `/etc/ssh/moduli`. Two immediate issues: there may be nothing in `/etc/ssh/moduli` and if there is the parameters may be less than 2048-bits. 

Two obvious solutions moving forward: 

1. Disable custom DH groups and **only** use curve25519
2. Accept a tradeoff and enable a NIST curve for compatibility

Given that OpenSSH 6.5 was released over two years ago ([2014-01-30](https://www.openssh.com/releasenotes.html)) I think 1 (above) is the preferable solution.

**Comment by 0xmikey** [comment]
The OP was in reference to `sshd_config` however we also need to change this in `ssh_config`.

**Comment by 0xmikey** [comment]
The commits above that reference this issue, ec4c3f12ec7e4d592f279804ea454926d036bd58 & 49c15c40800d5ed278bf340379a881273602c3e2, are for `ssh_config`.

The same changes were made to `sshd_config` by 76053ebb449b0e3b562761689461f4549825dc98 & 28a7672936c22fae50db5ffb0d7e4f51edd60610.

**Comment by egberts** [comment]
Should use the following lines...for sshd_config

```
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256

Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

# Following MACs does not work on Mac OSX 10.10 or older
MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha1

```

**Comment by 0xmikey** [comment]
@egberts thanks for the input, that and rereading [Secure Secure Shell](https://stribika.github.io/2015/01/04/secure-secure-shell.html) has me set on 
`KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256`.

`openssh.sh` now has a function `moduliCheck()` 552798421b99dd6551f006a34acf5a2766441692 that checks the moduli and if required generates a new one 37e9f2148f7293d362182852dc946cacc6b6999c. The original `moduli` file is backed up (per #9) before the script does anything 90c8cd638b28ff707e1468dbf0dc3be76e34d363.

Closing this issue, there is still some work left to do to finish `moduliCheck()` however that is separate.
